'use strict';

/* =========================================================
   1C AI Assistant — app.js
   Single source of truth for all site behavior.
   ========================================================= */

// -----------------------------------------------------------------
// Config
// -----------------------------------------------------------------
// URL of your own backend/serverless proxy that forwards to Groq
// (or any OpenAI-compatible API) and injects the API key server-side.
// See README.md / DEPLOY.md for how to set this up.
const CHAT_ENDPOINT = window.CHAT_ENDPOINT || '/api/chat';

const MAX_HISTORY_MESSAGES = 20;

// -----------------------------------------------------------------
// i18n
// -----------------------------------------------------------------
const i18n = {
  ru: {
    nav_features: 'Возможности',
    nav_install: 'Установка',
    nav_answers: 'Ответы',
    hero_title: 'ИИ-ассистент для 1С:Предприятия',
    hero_subtitle: 'Встройте искусственный интеллект в вашу учётную систему. Общайтесь с LLM прямо из интерфейса 1С.',
    hero_cta: 'Начать использовать',
    features_title: 'Возможности',
    install_title: 'Установка',
    chat_subtitle: 'Ответы на вопросы по проекту',
    chat_placeholder: 'Задайте вопрос о проекте...',
    chat_disclaimer: 'Ответы генерируются ИИ. Рекомендуется проверять информацию перед использованием.',
    chat_welcome: 'Привет! Я ИИ-ассистент проекта 1C AI Assistant.\n\nЗадавайте вопросы по проекту, установке и настройке.',
    chat_error: 'Не удалось подключиться к серверу. Попробуйте ещё раз.',
    features: [
      { icon: 'chat', title: 'Чат с ИИ внутри 1С', desc: 'Общайтесь с языковой моделью, не покидая интерфейс конфигурации.' },
      { icon: 'doc', title: 'Контекст объекта', desc: 'Задавайте вопросы по текущему справочнику, документу или отчёту.' },
      { icon: 'img', title: 'Работа с изображениями', desc: 'Прикрепляйте скриншоты и документы для анализа.' },
      { icon: 'server', title: 'On-premise шлюз', desc: 'Данные не покидают вашу инфраструктуру.' },
      { icon: 'link', title: 'Поддержка MCP', desc: 'Интеграция с инструментами через Model Context Protocol.' },
      { icon: 'history', title: 'История чата', desc: 'Все ответы сохраняются для повторного просмотра.' },
    ],
    send_label: 'Отправить',
    install: [
      'Импортируйте расширение CFE в конфигурацию 1С',
      'Разверните и запустите Go-шлюз на вашем сервере',
      'Укажите адрес шлюза в настройках 1С',
      'Откройте форму чата и начните диалог с ИИ',
    ],
  },
  en: {
    nav_features: 'Features',
    nav_install: 'Installation',
    nav_answers: 'Answers',
    hero_title: 'AI Assistant for 1C:Enterprise',
    hero_subtitle: 'Integrate artificial intelligence into your accounting system. Chat with LLM directly from the 1C interface.',
    hero_cta: 'Get Started',
    features_title: 'Features',
    install_title: 'Installation',
    chat_subtitle: 'Answers about the project',
    chat_placeholder: 'Ask a question about the project...',
    chat_disclaimer: 'Responses are generated by AI. Please verify information before use.',
    chat_welcome: "Hello! I'm the 1C AI Assistant.\n\nAsk questions about the project, installation and setup.",
    chat_error: 'Failed to reach the server. Please try again.',
    features: [
      { icon: 'chat', title: 'AI Chat in 1C', desc: 'Communicate with the language model without leaving the configuration interface.' },
      { icon: 'doc', title: 'Object Context', desc: 'Ask questions about the current catalog, document, or report.' },
      { icon: 'img', title: 'Image Support', desc: 'Attach screenshots and documents for analysis.' },
      { icon: 'server', title: 'On-premise Gateway', desc: 'Your data never leaves your infrastructure.' },
      { icon: 'link', title: 'MCP Support', desc: 'Integration with tools via Model Context Protocol.' },
      { icon: 'history', title: 'Chat History', desc: 'All responses are saved for later review.' },
    ],
    send_label: 'Send',
    install: [
      'Import the CFE extension into your 1C configuration',
      'Deploy and run the Go gateway on your server',
      'Specify the gateway address in 1C settings',
      'Open the chat form and start a dialogue with AI',
    ],
  },
};

const SUPPORTED_LANGS = Object.keys(i18n);

function getInitialLang() {
  let saved;
  try { saved = localStorage.getItem('lang'); } catch (_) { /* localStorage may throw in some environments */ }
  return SUPPORTED_LANGS.includes(saved) ? saved : 'ru';
}

let lang = getInitialLang();
let chatHistory = [];

function t(key) {
  return (i18n[lang] && i18n[lang][key]) || key;
}

// -----------------------------------------------------------------
// DOM refs (queried once)
// -----------------------------------------------------------------
const el = {
  splash: document.getElementById('splash'),
  navbar: document.getElementById('navbar'),
  hero: document.getElementById('hero'),
  langBtn: document.getElementById('langBtn'),
  featuresGrid: document.getElementById('features-grid'),
  installSteps: document.getElementById('install-steps'),
  chatMessages: document.getElementById('chatMessages'),
  chatInput: document.getElementById('chatInput'),
  sendBtn: document.getElementById('sendBtn'),
};

// -----------------------------------------------------------------
// Rendering: static content
// -----------------------------------------------------------------
function renderFeatures() {
  const grid = el.featuresGrid;
  const existingCards = grid.querySelectorAll('.card');

  i18n[lang].features.forEach((feature, i) => {
    let card = existingCards[i];
    if (!card) {
      card = document.createElement('div');
      card.className = 'card';
      card.style.animationDelay = `${i * 100}ms`;
      grid.appendChild(card);
    }

    let iconWrap = card.querySelector('.card-icon');
    if (!iconWrap) {
      iconWrap = document.createElement('div');
      iconWrap.className = 'card-icon';
      card.appendChild(iconWrap);
    }
    iconWrap.innerHTML = window.ICONS[feature.icon] || '';

    let title = card.querySelector('h3');
    if (!title) {
      title = document.createElement('h3');
      card.appendChild(title);
    }
    title.textContent = feature.title;

    let desc = card.querySelector('p');
    if (!desc) {
      desc = document.createElement('p');
      card.appendChild(desc);
    }
    desc.textContent = feature.desc;
  });
}

function renderInstall() {
  const list = el.installSteps;
  const existingSteps = list.querySelectorAll('.step');

  i18n[lang].install.forEach((stepText, i) => {
    let step = existingSteps[i];
    if (!step) {
      step = document.createElement('div');
      step.className = 'step';
      step.style.animationDelay = `${i * 100}ms`;
      list.appendChild(step);
    }

    let num = step.querySelector('.step-num');
    if (!num) {
      num = document.createElement('span');
      num.className = 'step-num';
      step.appendChild(num);
    }
    num.textContent = String(i + 1);

    let text = step.querySelector('.step-text');
    if (!text) {
      text = document.createElement('span');
      text.className = 'step-text';
      step.appendChild(text);
    }
    text.textContent = stepText;
  });
}

function applyLang() {
  document.documentElement.lang = lang;
  el.langBtn.textContent = lang === 'ru' ? 'EN' : 'RU';

  document.querySelectorAll('[data-i18n]').forEach((node) => {
    node.textContent = t(node.dataset.i18n);
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach((node) => {
    node.placeholder = t(node.dataset.i18nPlaceholder);
  });
  document.querySelectorAll('[data-i18n-aria-label]').forEach((node) => {
    node.setAttribute('aria-label', t(node.dataset.i18nAriaLabel));
  });

  renderFeatures();
  renderInstall();

  if (chatHistory.length === 0) {
    chatHistory = [{ role: 'assistant', content: t('chat_welcome') }];
  } else if (chatHistory[0].role === 'assistant') {
    chatHistory[0].content = t('chat_welcome');
  }
  renderMessages();
}

el.langBtn.addEventListener('click', () => {
  lang = lang === 'ru' ? 'en' : 'ru';
  localStorage.setItem('lang', lang);
  applyLang();
});



// -----------------------------------------------------------------
// Floating background symbols (decorative canvas)
// -----------------------------------------------------------------
(function initFloatingSymbols() {
  const canvas = document.getElementById('heroCanvas');
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  const SYMBOLS = ['{ }', '< />', '1C', 'AI', 'LLM', '()', '=>', '//', 'MCP', 'CFE'];

  let particles = [];

  function resize() {
    canvas.width = canvas.offsetWidth * devicePixelRatio;
    canvas.height = canvas.offsetHeight * devicePixelRatio;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.scale(devicePixelRatio, devicePixelRatio);
  }

  function createParticles() {
    const area = canvas.offsetWidth * canvas.offsetHeight;
    const isLowEnd = !window.matchMedia('(min-resolution: 1.5dppx)').matches && navigator.hardwareConcurrency <= 4;
    const maxParticles = isLowEnd ? 20 : 60;
    const count = Math.min(Math.floor(area / 25000), maxParticles);
    particles = Array.from({ length: count }, () => {
      const angle = Math.random() * Math.PI * 2;
      const speed = 0.15 + Math.random() * 0.35;
      return {
        x: Math.random() * canvas.offsetWidth,
        y: Math.random() * canvas.offsetHeight,
        symbol: SYMBOLS[Math.floor(Math.random() * SYMBOLS.length)],
        size: 10 + Math.random() * 12,
        vx: Math.cos(angle) * speed,
        vy: Math.sin(angle) * speed,
        targetVx: Math.cos(angle) * speed,
        targetVy: Math.sin(angle) * speed,
        opacity: 0.04 + Math.random() * 0.08,
        timer: 0,
        interval: 180 + Math.random() * 300,
      };
    });
  }

  function step() {
    ctx.clearRect(0, 0, canvas.offsetWidth, canvas.offsetHeight);
    particles.forEach((p) => {
      ctx.font = `${p.size}px Geist, monospace`;
      ctx.fillStyle = `rgba(255,255,255,${p.opacity})`;
      ctx.fillText(p.symbol, p.x, p.y);

      if (++p.timer >= p.interval) {
        p.timer = 0;
        p.interval = 180 + Math.random() * 300;
        const angle = Math.random() * Math.PI * 2;
        const speed = 0.15 + Math.random() * 0.35;
        p.targetVx = Math.cos(angle) * speed;
        p.targetVy = Math.sin(angle) * speed;
      }

      p.vx += (p.targetVx - p.vx) * 0.02;
      p.vy += (p.targetVy - p.vy) * 0.02;
      p.x += p.vx;
      p.y += p.vy;

      if (p.x < -80) p.x = canvas.offsetWidth + 80;
      if (p.x > canvas.offsetWidth + 80) p.x = -80;
      if (p.y < -40) p.y = canvas.offsetHeight + 40;
      if (p.y > canvas.offsetHeight + 40) p.y = -40;
    });
    requestAnimationFrame(step);
  }

  resize();
  createParticles();
  step();
  let resizeTimer;
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => { resize(); createParticles(); }, 150);
  });
})();

// -----------------------------------------------------------------
// Chat: markdown rendering (safe — escapes HTML before applying rules)
// -----------------------------------------------------------------
let codeBlockCounter = 0;

function escapeHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function parseMarkdown(raw) {
  if (!raw) return '';

  let text = escapeHtml(raw);
  codeBlockCounter = 0;

  // Fenced code blocks
  text = text.replace(/```(\w*)\n?([\s\S]*?)```/g, (_match, language, code) => {
    const id = `code-${codeBlockCounter++}`;
    const label = language ? `<span class="code-lang">${escapeHtml(language)}</span>` : '<span></span>';
    return (
      `<div class="code-block">` +
      `<div class="code-block-header">${label}` +
      `<button class="copy-btn" type="button" data-copy-target="${id}">⧉</button>` +
      `</div><pre><code id="${id}">${code.trim()}</code></pre></div>`
    );
  });

  // Inline code
  text = text.replace(/`([^`]+)`/g, '<code>$1</code>');

  // Headings
  text = text.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  text = text.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  text = text.replace(/^# (.+)$/gm, '<h1>$1</h1>');

  // Bold / italic
  text = text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  text = text.replace(/\*(.+?)\*/g, '<em>$1</em>');

  // Lists
  text = text.replace(/^- (.+)$/gm, '<li>$1</li>');
  text = text.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

  // Links — http(s) only, already-escaped text so this is safe as an href
  text = text.replace(/(https?:\/\/[^\s<]+)/g, '<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');

  text = text.replace(/\n/g, '<br>');
  return text;
}

// Event delegation for copy buttons — works for all messages, current and future.
el.chatMessages.addEventListener('click', (event) => {
  const btn = event.target.closest('.copy-btn');
  if (!btn) return;
  const targetId = btn.dataset.copyTarget;
  const codeNode = document.getElementById(targetId);
  if (!codeNode) return;

  navigator.clipboard.writeText(codeNode.textContent).then(() => {
    btn.textContent = '✓';
    setTimeout(() => { btn.textContent = '⧉'; }, 1500);
  });
});

// -----------------------------------------------------------------
// Chat: rendering messages
// -----------------------------------------------------------------
function appendMessage(message, animate) {
  const isUser = message.role === 'user';
  const row = document.createElement('div');
  row.className = `msg-row ${isUser ? 'user' : 'assistant'}${animate ? ' msg-new' : ''}`;
  const bubble = document.createElement('div');
  bubble.className = 'msg-bubble';
  bubble.innerHTML = parseMarkdown(message.content);
  row.appendChild(bubble);
  el.chatMessages.appendChild(row);
  el.chatMessages.scrollTop = el.chatMessages.scrollHeight;
}

function renderMessages() {
  const container = el.chatMessages;
  container.innerHTML = '';

  chatHistory.forEach((message, i) => {
    const isLatestReply = i === chatHistory.length - 1 && message.role === 'assistant' && chatHistory.length > 1;
    appendMessage(message, isLatestReply);
  });
}

function showTypingIndicator() {
  const row = document.createElement('div');
  row.className = 'msg-row assistant msg-new';
  row.id = 'typingIndicator';
  row.innerHTML = `
    <div class="typing-bubble">
      <span class="typing-dot"></span>
      <span class="typing-dot"></span>
      <span class="typing-dot"></span>
    </div>`;
  el.chatMessages.appendChild(row);
  el.chatMessages.scrollTop = el.chatMessages.scrollHeight;
}

function hideTypingIndicator() {
  document.getElementById('typingIndicator')?.remove();
}

// -----------------------------------------------------------------
// Chat: sending messages
// -----------------------------------------------------------------
function setSending(isSending) {
  el.sendBtn.disabled = isSending;
  el.chatInput.disabled = isSending;
}

async function sendMessage() {
  const text = el.chatInput.value.trim();
  if (!text) return;

  chatHistory.push({ role: 'user', content: text });
  el.chatInput.value = '';
  el.chatInput.style.height = 'auto';
  appendMessage({ role: 'user', content: text }, false);
  showTypingIndicator();
  setSending(true);

  const maxRetries = 2;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await fetch(CHAT_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          messages: chatHistory.slice(-MAX_HISTORY_MESSAGES),
          lang,
        }),
      });

      if (!response.ok) {
        throw new Error(`Server responded with ${response.status}`);
      }

      const data = await response.json();
      const reply = data.reply || t('chat_error');
      chatHistory.push({ role: 'assistant', content: reply });
      hideTypingIndicator();
      setSending(false);
      appendMessage({ role: 'assistant', content: reply }, true);
      el.chatInput.focus();
      return;
    } catch (err) {
      if (attempt < maxRetries) {
        await new Promise((r) => setTimeout(r, 1000));
        continue;
      }
      console.error('Chat request failed:', err);
      chatHistory.push({ role: 'assistant', content: t('chat_error') });
      hideTypingIndicator();
      setSending(false);
      renderMessages();
      el.chatInput.focus();
    }
  }
}


function autoResize() {
  el.chatInput.style.height = 'auto';
  el.chatInput.style.height = Math.min(el.chatInput.scrollHeight, window.innerHeight * 0.5) + 'px';
}

el.chatInput.addEventListener('input', autoResize);
autoResize();

el.chatInput.addEventListener('keydown', (event) => {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    sendMessage();
  }
});
el.sendBtn.addEventListener('click', sendMessage);

// -----------------------------------------------------------------
// Init
// -----------------------------------------------------------------
document.getElementById('chatCta')?.addEventListener('click', () => {
  document.getElementById('chat').scrollIntoView({ behavior: 'smooth' });
});

applyLang();

setTimeout(() => {
  el.splash.style.opacity = '0';
  setTimeout(() => { el.splash.style.display = 'none'; }, 300);
  el.navbar.style.opacity = '1';
  el.hero.style.opacity = '1';
}, 600);
